server.port = 5454

spring.application.name=Food-Delivery-App
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/feasto_food_app
spring.datasource.username=postgres
spring.datasource.password=010823

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect